# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: dox

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/dox
    binary: dox
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  footer: >-
    ---

    **Full Changelog**: https://github.com/g5becks/dox/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - repository:
      owner: g5becks
      name: homebrew-tap
    homepage: https://github.com/g5becks/dox
    description: Fetch library documentation files for AI agents
    license: MIT
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |-
      bin.install "dox"
    test: |-
      system "#{bin}/dox", "--version"
