# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: dox

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/dox
    binary: dox
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CONTRIBUTING.md

universal_binaries:
  - replace: true
    name_template: "{{ .ProjectName }}"

nfpms:
  - id: packages
    package_name: dox
    vendor: g5becks
    homepage: https://github.com/g5becks/dox
    maintainer: g5becks <https://github.com/g5becks>
    description: Fetch library documentation files for AI agents and indexing tools
    license: MIT
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    bindir: /usr/bin
    contents:
      - src: ./README.md
        dst: /usr/share/doc/dox/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/dox/LICENSE
      - src: ./CONTRIBUTING.md
        dst: /usr/share/doc/dox/CONTRIBUTING.md

brews:
  - repository:
      owner: g5becks
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/g5becks/dox
    description: Fetch library documentation files for AI agents and indexing tools
    license: MIT
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |-
      bin.install "dox"
    test: |-
      system "#{bin}/dox", "--version"

dockers:
  - image_templates:
      - "ghcr.io/g5becks/dox:{{ .Version }}-amd64"
      - "ghcr.io/g5becks/dox:latest-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Fetch library documentation files for AI agents"
      - "--label=org.opencontainers.image.url=https://github.com/g5becks/dox"
      - "--label=org.opencontainers.image.source=https://github.com/g5becks/dox"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
    dockerfile: Dockerfile

  - image_templates:
      - "ghcr.io/g5becks/dox:{{ .Version }}-arm64"
      - "ghcr.io/g5becks/dox:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Fetch library documentation files for AI agents"
      - "--label=org.opencontainers.image.url=https://github.com/g5becks/dox"
      - "--label=org.opencontainers.image.source=https://github.com/g5becks/dox"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
    dockerfile: Dockerfile

docker_manifests:
  - name_template: "ghcr.io/g5becks/dox:{{ .Version }}"
    image_templates:
      - "ghcr.io/g5becks/dox:{{ .Version }}-amd64"
      - "ghcr.io/g5becks/dox:{{ .Version }}-arm64"

  - name_template: "ghcr.io/g5becks/dox:latest"
    image_templates:
      - "ghcr.io/g5becks/dox:latest-amd64"
      - "ghcr.io/g5becks/dox:latest-arm64"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Performance Improvements
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: g5becks
    name: dox
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## dox {{ .Tag }}

    ### Installation

    **Homebrew (macOS/Linux):**
    ```bash
    brew install g5becks/tap/dox
    ```

    **Download Binary:**
    See assets below for your platform.

    **Docker:**
    ```bash
    docker pull ghcr.io/g5becks/dox:{{ .Tag }}
    ```
  footer: |
    ---

    **Full Changelog**: https://github.com/g5becks/dox/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Verifying the artifacts

    Download `checksums.txt` and verify with:
    ```bash
    sha256sum --check checksums.txt
    ```

announce:
  skip: "{{gt .Patch 0}}"
